apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 30s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    editable: true

  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    access: proxy
    url: http://victorialogs:9428
    jsonData:
      maxLines: 1000
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: victorialogs
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        tags: ['service.name', 'service']
        filterByTraceID: true
      tracesToProfilesV2:
        datasourceUid: pyroscope
        tags: ['service.name', 'service']
        profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    editable: true

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    url: http://pyroscope:4040
    editable: true
